-- auto-generated definition
CREATE TABLE daily_stock_data
(
    日期       date        NOT NULL,
    均价       double      NULL,
    昨收       double      NULL,
    最高       double      NULL,
    最低       double      NULL,
    总营收      double      NULL,
    总市值      double      NULL,
    总股本      double      NULL,
    主力净比     double      NULL,
    中单净比     double      NULL,
    涨停       double      NULL,
    涨幅       double      NULL,
    涨跌       double      NULL,
    营收同比     double      NULL,
    行业名称     varchar(64) NULL,
    小单净比     double      NULL,
    委差       double      NULL,
    委比       double      NULL,
    外盘       double      NULL,
    收益       double      NULL,
    市净率      double      NULL,
    上市日期     date        NULL,
    每股未分配利润  double      NULL,
    每股净资产    double      NULL,
    毛利率      double      NULL,
    流通市值     double      NULL,
    流通股数     double      NULL,
    量比       double      NULL,
    静态市盈率    double      NULL,
    净利润同比    double      NULL,
    净利润      double      NULL,
    净利率      double      NULL,
    今日主力净流入  double      NULL,
    今日中单净流入  double      NULL,
    今日小单净流入  double      NULL,
    今日大单净流入  double      NULL,
    今日超大单净流入 double      NULL,
    今开       double      NULL,
    换手率      double      NULL,
    滚动市盈率    double      NULL,
    股票名称     varchar(64) NULL,
    股票代码     varchar(64) NOT NULL,
    负债率      double      NULL,
    动态市盈率    double      NULL,
    跌停       double      NULL,
    地域板块名称   varchar(64) NULL,
    当日价格     double      NULL,
    大单净比     double      NULL,
    成交量      double      NULL,
    成交额      double      NULL,
    超大单净比    double      NULL,
    ROE      double      NULL,
    PRIMARY KEY (股票代码, 日期)
);