
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("304x453")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 453,
    width = 304,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    4.0,
    0.0,
    anchor="nw",
    text="This is a calculater designed by Sage!",
    fill="#000000",
    font=("Roboto", 18 * -1)
)

canvas.create_rectangle(
    2.0,
    214.0,
    61.0,
    273.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    2.0,
    304.0,
    61.0,
    363.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    2.0,
    394.0,
    61.0,
    453.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    83.0,
    124.0,
    142.0,
    183.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    83.0,
    214.0,
    142.0,
    273.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    83.0,
    304.0,
    142.0,
    363.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    83.0,
    394.0,
    142.0,
    453.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    164.0,
    124.0,
    223.0,
    183.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    164.0,
    214.0,
    223.0,
    273.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    164.0,
    304.0,
    223.0,
    363.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    164.0,
    394.0,
    223.0,
    453.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    245.0,
    124.0,
    304.0,
    183.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    245.0,
    214.0,
    304.0,
    273.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    245.0,
    304.0,
    304.0,
    363.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    245.0,
    394.0,
    304.0,
    453.0,
    fill="#000000",
    outline="")

canvas.create_text(
    264.0,
    400.0,
    anchor="nw",
    text="/",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    183.0,
    400.0,
    anchor="nw",
    text="=",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    22.0,
    400.0,
    anchor="nw",
    text="C",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    264.0,
    307.0,
    anchor="nw",
    text="x",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    264.0,
    220.0,
    anchor="nw",
    text="-",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    264.0,
    130.0,
    anchor="nw",
    text="+",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    101.0,
    400.0,
    anchor="nw",
    text="0",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    182.0,
    310.0,
    anchor="nw",
    text="9",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    101.0,
    310.0,
    anchor="nw",
    text="8",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    20.0,
    310.0,
    anchor="nw",
    text="7",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    182.0,
    220.0,
    anchor="nw",
    text="6",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    101.0,
    220.0,
    anchor="nw",
    text="5",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    20.0,
    220.0,
    anchor="nw",
    text="4",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    182.0,
    130.0,
    anchor="nw",
    text="3",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_text(
    101.0,
    130.0,
    anchor="nw",
    text="2",
    fill="#000000",
    font=("RobotoMono Regular", 36 * -1)
)

canvas.create_rectangle(
    0.0,
    124.0,
    63.0,
    190.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    2.0,
    46.0,
    304.0,
    92.0,
    fill="#000000",
    outline="")

canvas.create_text(
    275.0,
    50.0,
    anchor="nw",
    text="0",
    fill="#FFF9F9",
    font=("Roboto", 36 * -1)
)
window.resizable(False, False)
window.mainloop()